apiVersion: v1
data:
  client-id: '{{ .Values.github.clientID | b64enc }}'
  client-secret: '{{ .Values.github.clientSecret | b64enc }}'
  install-url: '{{ .Values.github.installURL | b64enc }}'
  integration-id: '{{ .Values.github.integrationID | b64enc }}'
kind: Secret
metadata:
  name: github-app
