apiVersion: batch/v1
kind: Job
metadata:
  name: ship-cluster-local-cluster
spec:
  template:
    spec:
      containers:
      - args:
        - /src/shipcloudctl
        - ensure-local-cluster
        env:
        - name: SHIP_API_ADVERTISE_ENDPOINT
          value: ""
        - name: POSTGRES_URI
          valueFrom:
            secretKeyRef:
              key: uri
              name: ship-enterprise-postgres
        - name: ENSURE_LOCAL_CLUSTER
          value: "1"
        image: registry.replicated.com/ship-enterprise/ship-cluster-api
        imagePullPolicy: IfNotPresent
        name: ship-cluster-local-cluster
      imagePullSecrets:
      - name: replicatedregistrykey
      restartPolicy: OnFailure
