apiVersion: databases.schemahero.io/v1alpha2
kind: Database
metadata:
  name: kotsadm-postgres
schemahero:
  image: schemahero/schemahero:0.7.2
  nodeSelector:
    replicated/node-pool: privileged
connection:
  postgres:
    uri:
      valueFrom:
        secretKeyRef:
          name: kotsadm-postgres
          key: uri
